imprement todo develop Project 20201201 ver000
7itoh/beTodo pull request #3
Opened 2020-12-01 01:53 UTC by 7itoh

課題3-3
main.js 実行中・完了の切り替え

2020-12-02 01:19 UTC, kouki-iwahara reviewed
コメントしましたのでご確認ください。

2020-12-02 01:19 UTC, kouki-iwahara commented on src/main.js
> +const sortTdList = (createTdValue,removedTdValue,stateTdValue) => {
`,`の後ろにはスペースを空けましょう。

また、sortTdListを実装する時、引数が一つしか渡っていないので、createTdValueしか現在使用されていないようです。
なので、
`else if (removedTdValue) {`
のように定義している意味も無いようです。

おそらく少し勘違いされていて、引数は名前ではなく順番で判定されます。
例えば
```
const hoge = (a, b) => {
  console.log('第一引数: ' + a);
  console.log('第二引数: ' + b);
};

const a = '値a';
const b = '値b';

hoge(b); 
// 結果
// '第一引数: 値b'
// '第二引数: undefined
```
のように、定義した第二引数と同じ名前を実行時に第一引数として渡しても、出力されるのは第一引数です。

2020-12-02 01:19 UTC, kouki-iwahara commented on src/main.js
>      Object.keys(todosInput).forEach((key, id) => {
配列todosを一度todosInputという変数に代入していますが、理由はなんでしょうか？
配列todosがグローバルで定義されておりますので、todos.forEach()で良いと思うのですが、できない理由などありますか？

2020-12-02 04:23 UTC, 7itoh commented on src/index.html
>              </fieldset>
index.htmlのフォームに<label>タグがなかったので追記しました。
こちら指摘とは、別な更新になります。

2020-12-02 04:26 UTC, 7itoh commented on src/main.js
> -    }
入力を分けていましたが削除しています。
以降の通り、「todos」からの入力処理へ統一しています。

なお削除前のコーディング理由は、「どこからの処理による入力値かの判定のため」になります。

2020-12-02 04:27 UTC, 7itoh commented on src/main.js
「todos.forEach」による処理へコード更新をしています。

2020-12-02 04:28 UTC, 7itoh commented on src/main.js
> +createTdList();
以下、追記をしています。
const createTdList = () => {}
createTdList();

2020-12-02 12:59 UTC, myzktkyk requested changes
指摘点の修正時に漏れていると思われる箇所があり、それが原因でエラーが出てしまっています。
再度修正をお願いします 🙏

2020-12-02 12:59 UTC, myzktkyk commented on src/main.js
> +        const todoContent = todos[key].content;
`Object.keys` から `forEach` に書き換え際にこちらも変更する必要があったのですが、漏れてしまっているようです…。

```
const todoContent = key.content;
```

forEach の仕様は以下を確認されるとよいと思います。
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach

2020-12-03 01:24 UTC, 7itoh commented on src/main.js
> +        const todoDelete = key.delete;
指摘コードへの修正をしています。
> const todoContent = key.content;

2020-12-04 01:34 UTC, kouki-iwahara reviewed
コメントしましたのでご確認ください。

2020-12-04 01:34 UTC, kouki-iwahara commented on src/main.js
> +    todos.forEach((key, id) => {
コールバックの引数名が抽象的なのと名前に違和感があります。
第一引数にはtodosの中身が、第二引数にはindexが入るので
`todos.forEach((todo, index) => {`
とすると可読性が高くなります。
（indexはidxと略されることもあるので、そちらでも良いです。）

2020-12-04 01:41 UTC, merged